name = "music-fest"
routes = ['musicfest.josephtseng-tw.com/*']
account_id = "1f7783c7c3c593ab98bad669c80ae933"
workers_dev = true
compatibility_date = "2022-03-11"
main = "workers-site/index.js"
site = { bucket = "./out" }
