name: Building test

on:
  pull_request:
    branches:
      - main


env:
  REACT_APP_MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}

jobs:
  build-app:
    name: Setup and Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Build
        run: |
          yarn install && yarn build && yarn export
